version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
